version: '2'

volumes:
    logs:
        driver: local

services:
    backend-php-server:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8889
        volumes:
            - .:/var/www
            - logs:/var/www/logs
